apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: vmsingle
spec:
  retentionPeriod: "2"
  removePvcAfterDelete: true
  nodeSelector:
    system-node: "true"
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi