server:
  replicas: 2
  authModes: ["server"]
  nodeSelector:
    system-node: "true"
controller:
  replicas: 2
  nodeSelector:
    system-node: "true"
workflow:
  serviceAccount:
    create: true # Specifies whether a service account should be created
  rbac:
    create: true # adds Role and RoleBinding for the above specified service account to be able to run workflows