{
 "title": "Rclone Akamai Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Customer",
    "label": "Customer",
    "query": {
     "query": "label_values(rclone_speed,customer)"
    }
   },
   {
    "name": "SelectedPods",
    "label": "SelectedPods",
    "query": {
     "query": "label_values(rclone_speed{customer=\"$Customer\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Total Rclone Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rclone_checked_files_total{customer=\"$Customer\"})",
     "legendFormat": "Files Checked"
    },
    {
     "expr": "sum(rclone_files_transferred_total{customer=\"$Customer\"})",
     "legendFormat": "Files Transferred"
    },
    {
     "expr": "sum(rclone_files_deleted_total{customer=\"$Customer\"})",
     "legendFormat": "Files Deleted"
    },
    {
     "expr": "sum(rclone_dirs_deleted_total{customer=\"$Customer\"})",
     "legendFormat": "Directories Deleted"
    },
    {
     "expr": "sum(rclone_files_renamed_total{customer=\"$Customer\"})",
     "legendFormat": "Files Renamed"
    },
    {
     "expr": "sum(rclone_errors_total{customer=\"$Customer\"})",
     "legendFormat": "Total Errors"
    }
   ]
  },
  {
   "title": "Data Tranferred",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(rclone_bytes_transferred_total{customer=~\"$Customer\"}[$__range]))",
     "legendFormat": "Range"
    },
    {
     "expr": "sum(increase(rclone_bytes_transferred_total{customer=~\"$Customer\"}[24h] @ end()))",
     "legendFormat": "24h"
    },
    {
     "expr": "sum(increase(rclone_bytes_transferred_total{customer=~\"$Customer\"}[300000h] @ end()))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Number of Files Transferred",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(rclone_files_transferred_total{customer=~\"$Customer\"} [$__range]))\n\n",
     "legendFormat": "Range"
    },
    {
     "expr": "sum(increase(rclone_files_transferred_total{customer=~\"$Customer\"}[24h] @ end()))\n",
     "legendFormat": "24h"
    },
    {
     "expr": "sum(increase(rclone_files_transferred_total{customer=~\"$Customer\"}[30000h] @ end()))\n",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Rclone running since",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(process_start_time_seconds{customer=\"$Customer\"}) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rclone_speed{customer=\"$Customer\"})",
     "legendFormat": "Total Traffic rate"
    }
   ]
  },
  {
   "title": "Transfer Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rclone_speed{customer=\"$Customer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 7 },
   "targets": [
    {
     "expr": "sum(rclone_checked_files_total{customer=\"$Customer\"})",
     "legendFormat": "Files Checked"
    },
    {
     "expr": "sum(rclone_files_transferred_total{customer=\"$Customer\"})",
     "legendFormat": "Files Transferred"
    },
    {
     "expr": "sum(rclone_files_deleted_total{customer=\"$Customer\"})",
     "legendFormat": "Files Deleted"
    },
    {
     "expr": "sum(rclone_dirs_deleted_total{customer=\"$Customer\"})",
     "legendFormat": "Directories Deleted"
    },
    {
     "expr": "sum(rclone_files_renamed_total{customer=\"$Customer\"})",
     "legendFormat": "Files Renamed"
    },
    {
     "expr": "sum(rclone_errors_total{customer=\"$Customer\"})",
     "legendFormat": "Total Errors"
    }
   ]
  },
  {
   "title": "Parallel Rclone Jobs",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(increase(count by (pod) (up{pod=~\"$SelectedPods\"})[$__range]))\n",
     "legendFormat": "Max parallel jobs"
    },
    {
     "expr": "count(count by (pod) (up{pod=~\"$SelectedPods\"}))",
     "legendFormat": "Current parallel jobs"
    }
   ]
  },
  { "title": "Rclone Metrics per Pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Transferred data per Job",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rclone_bytes_transferred_total{pod=~\"$SelectedPods\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of files Transferred per Job",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "rclone_files_transferred_total{pod=~\"$SelectedPods\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transfer Rate per Job",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rclone_speed{pod=~\"$SelectedPods\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of Errors per Job",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 11, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "rclone_errors_total{pod=~\"$SelectedPods\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{image!=\"\", name=~\"^k8s_.*\", pod=~\"$SelectedPods\"}[5m]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pod Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",pod=~\"$SelectedPods\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Historical Instances",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 14, "y": 24 },
   "targets": [
    { "expr": "rclone_speed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pod Network Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(sum(container_network_receive_bytes_total{image!=\"\", name=~\"^k8s_.*\", pod=~\"$SelectedPods\"})[1m]))",
     "legendFormat": "-> Total Bandwidth-In"
    },
    {
     "expr": "- sum by(pod) (rate(sum(container_network_receive_bytes_total{image!=\"\", name=~\"^k8s_.*\", pod=~\"$SelectedPods\"})[1m]))",
     "legendFormat": "<- Total Bandwidth-Out"
    }
   ]
  },
  {
   "title": "Pod Network Packet Rate I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(sum(container_network_receive_packets_total{image!=\"\",name=~\"^k8s_.*\",pod=~\"$SelectedPods\"}) [1m]))",
     "legendFormat": "-> Total Network Packets - In"
    },
    {
     "expr": "- sum by(pod) (rate(sum(container_network_receive_packets_total{image!=\"\",name=~\"^k8s_.*\",pod=~\"$SelectedPods\"}) [1m]))",
     "legendFormat": "<- Total Network Packets - Out"
    }
   ]
  },
  {
   "title": "Pod Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(sum(container_network_receive_packets_dropped_total{image!=\"\", name=~\"^k8s_.*\", pod=~\"$SelectedPods\"})[1m]))",
     "legendFormat": "-> Total Packets Dropped - In"
    },
    {
     "expr": "- sum by(pod) (rate(sum(container_network_receive_packets_dropped_total{image!=\"\", name=~\"^k8s_.*\", pod=~\"$SelectedPods\"})[1m]))",
     "legendFormat": "<- Total Packets Dropped - Out"
    }
   ]
  }
 ]
}